# Generated by Django 4.2.6 on 2023-11-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batasdesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunanpogung',
            name='jenis',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bangunanpogung',
            name='nama',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bangunanpogung',
            name='pemilik',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
