# Generated by Django 4.2.6 on 2023-11-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0002_remove_restoran_lat_remove_restoran_long'),
        ('batasdesa', '0002_alter_bangunanpogung_jenis_alter_bangunanpogung_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunanpogung',
            name='pemilik',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='peta.restoran'),
        ),
    ]
